language: dart

dist: bionic

install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
  - ./flutter/bin/cache/dart-sdk/bin/dartanalyzer . | internal/static_analyzer.sh

script:
  - echo "Begin script"
  - ./flutter/bin/flutter test

cache:
  directories:
    - $HOME/.pub-cache
