name: app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.12.0+4
  cupertino_icons: ^0.1.2
  provider: ^4.0.1
  sqflite: ^1.2.0
  firebase_storage:
    git:
      url: git://github.com/danysz/flutterfire.git
      ref: master
      path: packages/firebase_storage
  logger: ^0.8.3
  google_fonts: ^0.3.2
  flutter_svg: ^0.16.1
  path_provider: ^1.6.0
  dio: ^3.0.8
  archive: ^2.0.11
  url_launcher: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/menu.svg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
